name: Andrewcoates
favicon: null
layout_spectrum: 0.25459
typography_spectrum: 0.48998
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#17a599'
    - '#cd0835'
    - '#2e0f17'
    - '#f97d01'
  brandStrength: 0.5
  lightness: 0.125
  saturation: 0.5625
  rhythmicContrast: 0.75
purpose: []
