name: Andrewcoates
favicon: null
layout_spectrum: 0.17182792373932898
typography_spectrum: 0.6296869006473571
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.2718231847975403
  lightness: 0.14368588640354574
  saturation: 0.4811991744209081
  rhythmicContrast: 0.7502579486463219
purpose: []
